### ISSUE TITLE
The Readme.md file is it up to date ?

### ISSUE THREAD

**Issue by LaurentDardenne** [BernieWhite/PSRule#179]
Hi,
i try to use your code but, the documentation seem to be not to up to date
```Powershell
Rule 'isFruit' {
     # An additional message to display in output
     Hint 'Fruit is only Apple, Orange and Pear'

     # Condition to determine if the object is fruit
     $TargetObject.Name -in 'Apple', 'Orange', 'Pear'
}
```
I get this error :
```
Rule : This keyword can only be called within PSRule. To call rules use Invoke-PSRule.
```
The original documentation dont specify to use a file :
```Powershell
$items = @();
$items += [PSCustomObject]@{ Name = 'Fridge' };
$items += [PSCustomObject]@{ Name = 'Apple' };
$items | Invoke-PSRule 
```
I get a warning
```
AVERTISSEMENT : Path not found
```
Now I use a file :
```Powershell
@'
Rule 'isFruit' {
     # An additional message to display in output
     Hint 'Fruit is only Apple, Orange and Pear'

     # Condition to determine if the object is fruit
     $TargetObject.Name -in 'Apple', 'Orange', 'Pear'
}
'@ >  c:\temp\Test.ps1

$items = @();
$items += [PSCustomObject]@{ Name = 'Fridge' };
$items += [PSCustomObject]@{ Name = 'Apple' };
$items | Invoke-PSRule -Path c:\temp\Test.ps1
```
I get a warning :
```
AVERTISSEMENT : Path not found
```
After read the test folder, the file must be ended  with 'Rule'.
```Powershell
@'
Rule 'isFruit' {
     # An additional message to display in output
     Hint 'Fruit is only Apple, Orange and Pear'

     # Condition to determine if the object is fruit
     $TargetObject.Name -in 'Apple', 'Orange', 'Pear'
}
'@> c:\temp\Test.Rule..ps1

$items = @();
$items += [PSCustomObject]@{ Name = 'Fridge' };
$items += [PSCustomObject]@{ Name = 'Apple' };
$items | Invoke-PSRule -Path c:\temp\Test.Rule.ps1
```
Ok :-)
The warning message do not specify the namming rule of a rule file.
Have you plan to allow the use of a scriptblock (dynamic rules) with Invoke-PSRule and not only a file ?

Windows 10 Fr (1803)
psrule v0.6.0
PS v5.1

**Comment by BernieWhite** [comment]
@LaurentDardenne Thanks for the feedback. I'll see if I can make changes to readme.md to make that clearer.

Yes `Rule` blocks need to be in a `.Rule.ps1` file. Currently there is no plans to change that, mainly because rules are designed to be reusable, and it makes it a lots more complicated if they are not in a file. Also this follows a similar pattern to Pester and other tools.

If you have a good use case that Rule blocks should not be in files then maybe that would change?

**Comment by LaurentDardenne** [comment]
> If you have a good use case that Rule blocks should not be in files then maybe that would change?

I will use files in this case :-)
I continue to study your module, it was just a first impression/feedback.

Anyway thank you for your module, I think it will please many people because it fills a gap.
