### ISSUE TITLE
Invoke-PsRule throw a System.InvalidCastException when a Rule send 2 objects into the pipeline.

### ISSUE THREAD

**Issue by LaurentDardenne** [BernieWhite/PSRule#187]
Invoke-PsRule throw a System.InvalidCastException when a Rule send 2 objects into the pipeline.

To reproduce the error :
```Powershell
$Path='C:\temp'
$File='Test.Rule.ps1'
@'
Rule Test {
  'test' #or a return value of a method call
  $true
}
#same error with this code
# Rule Test2 {
#   $true
#   'test'

#No error with this code
# Rule Test2 {
#   $true
#   $true
#}
'@ >"$Path\$File"

'data'|Invoke-PSRule -Path "$Path\$File"
#Invoke-RuleBlock : Le cast spécifié n'est pas valide.
# Au caractère C:\....\Modules\psrule\0.7.0\PSRule.psm1:171 : 17
# +                 $pipeline.Process($InputObject);
# +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     + CategoryInfo          : NotSpecified: (:) [Invoke-RuleBlock], InvalidCastException
#     + FullyQualifiedErrorId : System.InvalidCastException,PSRule.Commands.InvokeRuleBlockCommand
```
The details of the exception :
```Powershell
$e=$error[0]
$e|select *

# PSMessageDetails      :
# Exception             : System.InvalidCastException: Le cast spécifié n'est pas valide.
#                            à PSRule.Rules.RuleConditionResult.Create(IEnumerable`1 value)
#                            à PSRule.Commands.InvokeRuleBlockCommand.ProcessRecord()
#                            à System.Management.Automation.CommandProcessor.ProcessRecord()
# TargetObject          :
# CategoryInfo          : NotSpecified: (:) [Invoke-RuleBlock], InvalidCastException
# FullyQualifiedErrorId : System.InvalidCastException,PSRule.Commands.InvokeRuleBlockCommand
# ErrorDetails          :
# InvocationInfo        : System.Management.Automation.InvocationInfo
# ScriptStackTrace      :
# PipelineIterationInfo : {}


$e.Exception|select *

# Message        : Le cast spécifié n'est pas valide.
# Data           : {}
# InnerException :
# TargetSite     : PSRule.Rules.RuleConditionResult Create(System.Collections.Generic.IEnumerable`1[System.Object])
# StackTrace     :    à PSRule.Rules.RuleConditionResult.Create(IEnumerable`1 value)
#                     à PSRule.Commands.InvokeRuleBlockCommand.ProcessRecord()
#                     à System.Management.Automation.CommandProcessor.ProcessRecord()
# HelpLink       :
# Source         : PSRule
# HResult        : -2147467262
```

**Expected behaviour**
[The documentation for the word Rule ](https://github.com/BernieWhite/PSRule/blob/master/docs/keywords/PSRule/en-US/about_PSRule_Keywords.md#rule)does not specify whether a rule should issue a single return value of type boolean ($true or $false) or multiple values of type boolean.
In this case it is the last issued value that takes precedence.

**Comment by BernieWhite** [comment]
@LaurentDardenne :) you are testing my documentation, thanks keep it up.

Rule conditions can only return `$True` or `$False`, so the string `test` is not valid. Good catch.

When more then condition is defined if any return `$False` then the rule failed. If all return `$True` then the rule passed.

So, the following would always fail, regardless of the `$True` being the last condition.

```text
Rule 'Test' {
$False
$True
}
```

As you have pointed out, the rule keyword documentation isn't clear. Thanks. I'll look to correct that.

The [walkthrough](https://github.com/BernieWhite/PSRule/blob/master/docs/scenarios/azure-resources/azure-resources.md#set-rule-condition) is hopefully a little clearer.

- [ ] Improve messaging for non-boolean return types from conditions.
- [ ] Fix rule keyword documentation.

**Comment by LaurentDardenne** [comment]
> The walkthrough is hopefully a little clearer.

_Rome wasn't built in a day_ :-)

Thanks.

**Comment by LaurentDardenne** [comment]
Thanks for this fix. I have just one remark.

With the version 0.7.0-B190633 :
```powershell
$r='data'|Invoke-PSRule -Path "$Path\$File" -Outcome all
# Invoke-PSRule : An invalid rule result was returned for Test.Rule.ps1/Test. Conditions must return boolean $True or $False.
#...
#     + FullyQualifiedErrorId : PSRule.Runtime.InvalidRuleResult,Invoke-PSRule

$r|select *
# Outcome        : Fail
# OutcomeReason  : Processed
#...
# RuleId         : Test.Rule.ps1/Test
# RuleName       : Test
```
In this case I have a Powershell error, but the OutCome content is 'fail'
What difference do you make here between ['Fail' and 'Error'](https://github.com/BernieWhite/PSRule/blob/master/src/PSRule/Rules/RuleOutcome.cs#L30) ?
Or under what conditions do I have the OutCome content at 'Error'?

**Comment by BernieWhite** [comment]
@LaurentDardenne Good call out. Agreed it should return the error status instead of fail. I think it is fair to say that if an error in rule or in engine occurs during an rule execution then the `Error` outcome should be returned.
