### ISSUE TITLE
[Question] About OutCome and OutComeReason

### ISSUE THREAD

**Issue by LaurentDardenne** [BernieWhite/PSRule#195]
I'm trying to list the different results that Invoke-PSRule can return, but some cases (enum RuleOutcomeReason) seem to me not to be generated:
```Powershell
$Path='C:\temp'
$File='Test.Rule.ps1'
@'
Rule Test -if {$true} {
 $true
}

Rule Test1 -if {$true} {
    $false
}

Rule Test2 -if {$true} {

}

Rule Test3 -if {$false} {

}

Rule Test4 -if {} {

}

Rule Test5 -if {$null} {

}

Rule Test6  {
  1/0
}

Rule 'WithDependency2' -DependsOn 'WithDependency5' {
    # Pass
    $True;
}

# Synopsis: Fail
Rule 'WithDependency5' {
    # Fail
    $False
}
'@ >"$Path\$File"
$Result='object'|Invoke-PSRule -path "$Path\$File" 
$Result|Select-Object RuleName,Outcome,OutcomeReason
# RuleName        Outcome OutcomeReason
# --------        ------- -------------
# Test               Pass     Processed
# Test1              Fail     Processed
# Test2              Fail  Inconclusive
# WithDependency5    Fail     Processed
```
I [read](https://github.com/BernieWhite/PSRule/blob/master/docs/scenarios/azure-resources/azure-resources.md#filter-with-preconditions) that some are skipped but we do not know it in the end result.
And I can not find those in error unless parsing the $Error collection or those '_DependencyFail_' or '_PreconditionFail_' unless they are internal states.

**Comment by BernieWhite** [comment]
@LaurentDardenne Rules skipped due to preconditions haven't be executed so the outcome is None which is filtered by default.

Try adding `-Outcome All`.

**Comment by LaurentDardenne** [comment]
Thank you.
