### ISSUE TITLE
Include use of keywords within If pre-conditions

### ISSUE THREAD

**Issue by LaurentDardenne** [BernieWhite/PSRule#203]
May be specify that the _If_ parameter of a _**Rule**_ can contains Keywords except 'Rule' : 
```Powershell
$Path='C:\temp'

$Rule='Test.Rule.ps1'
@'
Rule 'validatePhoneNumber' -if {Exists PhoneNumber} {
          Match 'PhoneNumber' '^(\+61|0)([0-9] {0,1}){8}[0-9]$'
}
'@ >"$Path\$Rule"
[PSCustomObject]@{PSTypeName='My';name='Test'},[PSCustomObject]@{PSTypeName='My';PhoneNumber='01'}|Invoke-PSRule -path "$Path\$Rule" 
```

**Comment by BernieWhite** [comment]
@LaurentDardenne Just checking if I understand you correctly. Your suggestion is to add documentation about the usage of keywords in if pre-conditions?

**Comment by LaurentDardenne** [comment]
Exact.
It's implied today, but I thought the body of a rule was differently analyzing a scriptblock.

**Comment by BernieWhite** [comment]
Currently use of keywords within script (`If`) preconditions is not included in unit tests. Use of `Exists`, `Within`, `Match` and `TypeOf` can be used within script preconditions, so we should expand unit tests to cover this scenario.

`Recommend`, `Reason` and `Rule` keywords are not valid in script pre-conditions.
