### ISSUE TITLE
[Feature request] Within assertion : add a -Not parameter

### ISSUE THREAD

**Issue by LaurentDardenne** [BernieWhite/PSRule#208]
With this operator I can not express 'All but'
If from a list of 10 values I want to exclude a single value, with this operator I must enter 9 values instead of one.

Maybe also add -Not for the _Match_ assertion.

**Comment by BernieWhite** [comment]
@LaurentDardenne Nice suggestion.

**Comment by BernieWhite** [comment]
@LaurentDardenne For `Within` a `-DisallowedValue` parameter I think will make more sense since the positive form is `-AllowedValue`. For `Match` a `-Not` switch still makes the most sense.

**Comment by BernieWhite** [comment]
On second thoughts it will be more consistent across each keyword to go with your original suggestion of `-Not` and rename the `-AllowedValue` parameter to `-Value`.
